### ISSUE TITLE
[bug?] 使用 rssant 订阅 https://rsshub.app/rsshub/routes 显示  -206 FEED_CONNECTION_RESET when request '

### ISSUE THREAD

**Issue by radiorz** [anyant/rssant#120]
### 环境
- rssant 1.8.8
### question
使用 rssant 订阅 https://rsshub.app/rsshub/routes 显示 -206 FEED_CONNECTION_RESET when request ' 
是因为 https么?
如何解决?

**Comment by guyskk** [comment]
试了一下蚁阅在线版订阅正常。你是自己部署的吗？大概是 rsshub.app 被墙了，你的服务器连接不上它。

**Comment by radiorz** [comment]
自己部署在windows 上 < 但是我通过 windows 的 fluent reader客户端 可以上

**Comment by radiorz** [comment]
谢谢.  确实是被墙了 笔记本连接了另一个wifi

**Comment by radiorz** [comment]
换了网络, 使用 网页 ,rss 客户端都可以连接上 rsshub.app
但是 部署在docker上的rssant 就是连接不上 ,还是没有排查处原因
我的 docker-compose 如下
```yml
# yaml 配置
version: '3'
services:
  # rsshub
  rsshub:
    container_name: diygod_rsshub
    image:  diygod/rsshub:2022-03-08
    environment:
      - TZ=Asia/Shanghai
    ports:
      - 29999:1200
    networks: 
      rss_net:
        ipv4_address: 172.19.0.3      
    # expose:
    #   - 1200
    restart: always
  rssant:
    container_name: rssant
    image: guyskk/rssant:1.8.8
    environment:
      - TZ=Asia/Shanghai
    env_file: 
      - ./rssant/rssant.env
    volumes:
      - rssant-data:/app/data
      - rssant-postgres-data:/var/lib/postgresql/11/main
      - rssant-postgres-logs:/var/log/postgresql
    ports:
      - 6789:80
    restart: always
    networks:
      rss_net:
        ipv4_address: 172.19.0.2     
    healthcheck: 
      test: "curl http://172.9.0.3:1200 || exit 0"
    links:
      - rsshub:diygod_rsshub
    logging:
      driver: "json-file"
      options:
        max-size: 50m
        max-file: 10
    # external_links:
    #   - diygod_rsshub
    depends_on:
      - diygod_rsshub
volumes:
  rssant-data:
  rssant-postgres-data:
  rssant-postgres-logs:
networks:
   rss_net:
      name: rss_net
      driver: bridge
      ipam:
        config:
          - subnet: 172.19.0.0/24
            gateway: 172.19.0.1
```
另外 rssant
